require 'rake'
require 'puppet-lint'
require 'rspec/core/rake_task'
#require 'puppetlabs_spec_helper/rake_tasks'

RSpec::Core::RakeTask.new(:spec) do |t|
  t.pattern = 'spec/*/*_spec.rb'
end


desc "Run lint check on puppet manifests"
task :lint do
linter =  PuppetLint.new
  Dir.glob('./manifests/*.pp').each do |puppet_file|
    puts "Evaluating #{puppet_file}"
    linter.file = puppet_file
    linter.run
    puts "------------------------------------------------------"
  end
  fail if linter.errors?
 end